open-quantum-safe/tsc

config.yaml

As per vote in 20 APR 2024 meeting

Add Vlad Gheorghiu to the TSC

---

README.md

I forgot to update the readme.

Add Vlad Gheorghiu to the roster

---

config.yaml

Sets visibility of www repo to public (anyone can view and raise PRs)
Fixes #20

Update visibility of www repo to public

---

config.yaml

Add triage team

---

config.yaml

This addresses CLOWarden issues.

Add TSC to read role

---

config.yaml

Add core: read

---

config.yaml

Update TSC, core access to WWW

---

meetings/2024-06-27/minutes.md

Initial version of the minutes of June 27, 2024. Asking for feedback as to which parts should be further fleshed out. Otherwise, please approve.

Minutes for June 27, 2024 meeting

---

config.yaml

Give pi-314159 write access on oqs-demos

---

meetings/2024-09-10/agenda.md
meetings/index.md

Less than a week to go, so I lost my cool and publish sth for general information/feedback @dstebila 
I'd also suggest having a conversation as to the general interest/willingness to contribute to discussions in GH (both to support the community as well as to prepare for productive meetings): This participation is IMO pretty low.

agenda draft

---

config.yaml

See https://github.com/open-quantum-safe/liboqs/pull/1943.
-    sub project contributors (incl. code owners) have write …

Update liboqs-codeowners per liboqs PR #1943

---

config.yaml

To implement #102 in config.yaml.
Closes #96.
-    sub project contributors (incl. code owners) have write rights on all …

Add @SWilson4 to TSC team

---

meetings/2024-11-05/minutes.md

Minutes for the OQS Technical Steering Committee meeting held on 2024-11-05.

Draft minutes for 2024-11-05 TSC meeting

---

README.md
meetings/2025-01-14/agenda.md
meetings/index.md

@open-quantum-safe/tsc Feedback and suggestions welcome

Add first draft of TSC agenda 2025-01-14

---

oqs-status-meetings/2025-02-18 - OQS status meeting - minutes.md

Thanks to Basil for taking minutes!

Add minutes for 2025-02-18 status meeting

---

README.md
config.yaml

@brian-jarvis-aws emailed me to step down from his role on the OQS TSC.
-    sub project contributors (incl. code owners) …

Remove Brian Jarvis from OQS TSC

---

oqs-status-meetings/2025-05-06 - OQS status meeting - minutes.md

-    sub project contributors (incl. code owners) have write rights on all branches except main on those sub projects
- …

Add meeting minutes - May 6 OQS status update

---

meetings/2025-04-29/minutes.md

Minutes for the 2025-04-29 TSC meeting.

2025-04-29 TSC minutes

---

meetings/2025-08-12/minutes.md

-    sub project contributors (incl. code owners) have write rights on all branches except main on those sub projects
- …

Add 2025-08-12 TSC meeting minutes

---

config.yaml

See https://github.com/open-quantum-safe/liboqs/pull/2176
-    sub project contributors (incl. code owners) have write …

Add saitomst to CODEOWNERS for liboqs NTRU implementation
