open-quantum-safe/tsc

governance/approved_licenses.md

The [OQS Technical Charter](https://github.com/open-quantum-safe/tsc/blob/main/charter/) section 7.a.i specifies that all inbound and outbound code contributions to the Project must be made using the MIT License.  
Section 7.c permits the TSC to approve the use of an alternative license for inbound or outbound contributions on an exception basis.
This pull request creates a file in the tsc repository tracking the list of approved license exemptions and grants an exemption to contribute code to the open-quantum-safe/boringssl repository using the licenses in the LICENSE file contained in that repository.  
Partially fixes #13.
I've submitted this as a draft pull request for now to get feedback on whether this is an agreeable approach; @hartm what do you think? If it seems okay, then I'll …

VOTE: License exemption for OQS-BoringSSL

---

README.md
meetings/index.md

This PR adds a simple link on the front page to a minutes & agenda page
That page then provides links to the agenda and minutes of each meeting (latest first)
We may want to adopt more sophisticated layout, but this could be a first step.
NOTE: This does include links to files that are currently in review but felt it better to separate this proposal from the review of the minutes themselves

Add link to minutes and basic index

---

config.yaml

Amber Sprenkels @dsprenkels had been contributing to the liboqs-rust repository but is not able to actively help out at this time, so we can remove her for now and add her back if she becomes more available to help.

Remove Amber Sprenkels from liboqs-rust

---

config.yaml

@dstebila is a placeholder maintainer of a few teams until the members join the org.

More team cleanup

---

meetings/2024-04-10/minutes.md

Adds an initial version of the minutes from 2024-04-10
@ryjones @dstebila can you point me to/share the meeting recording/transcript & I'll update with any omissions.

Add 20240410 minutes

---

config.yaml

As recommend during today's oqs call, I believe this will give me the correct access to edit projects, labels, and assignees in the oqs-demos repo (and based on this config it seems every OQS repo)

Add @ajbozarth to triage members

---

config.yaml

- Give @geedo0 write access to https://github.com/open-quantum-safe/openssh. Gerardo is actively working on bringing the openssh project up to date.
- Give @geedo0 triage access across OQS projects.
- Give @jplomas read access to liboqs, and hence the ToB project board. JP is a regular attendee on liboqs status calls.

Upgrade access for OQS project non--core-team members

---

config.yaml

This creates a new private repository to work on integrating NVIDIA's cupqc in liboqs. This work shall remain private temporarily at NVIDIA's request to not expose the API calls against cupqc before it is merged into liboqs main.
Users with write access:
- @praveksharma
- @ydoroz
- @stevenireeves
- @neil-lindquist

Create new private liboqs-cupqc repository

---

config.yaml

This would allow me to upload meeting minutes without requiring a TSC member to approve the PR.
I'll leave it to @open-quantum-safe/tsc to decide whether or not this is appropriate.

Give @SWilson4 write permissions on tsc repo to push meeting minutes

---

config.yaml

This will allow CI for those repos to be triggered from liboqs CI.

Give oqs-bot access to liboqs-cpp and liboqs-go

---

.github/pull_request_template.md
CODEOWNERS
config.yaml

Fixes #10 as per https://github.com/open-quantum-safe/tsc/issues/10#issuecomment-2339400591 
Draft only pending TSC agreement

implementing #10

---

config.yaml

Thomas Bailleux has updated to a new GitHub account.
Old account: thb-sb
New account: zadlg
-    sub project contributors …

Update github account for thb

---

config.yaml

See https://github.com/open-quantum-safe/tsc/pull/77#discussion_r1780535657. Marked as draft pending input from @thomwiggers on whether or not the name change (liboqs-rust-release-managers -> rust) is necessary.
-    sub project committers have write rights on …

Document dependency on liboqs-rust Release Managers team

---

config.yaml

This will stop flapping in CLOWarden
The security managers (the TSC) need read access to all repos
-    sub project …

Add security managers to repo

---

README.md

This pull request is a TSC vote to add Spencer Wilson to the OQS TSC and appoint him to be the OQS representative to the PQCA TAC.  
Voting members for this issue:
- @ashman-p 
- @baentsch 
- @zadlg 
- @vsoftco 
- @bhess 
- @brian-jarvis-aws 
- @christianpaquin 
To vote in favour, please either give a positive review or a thumbs up on this comment. To vote against, please give a thumbs down on this comment. Quorum is 5 votes.

VOTE: Add Spencer Wilson to OQS TSC and appoint as OQS rep to PQCA TAC

---

config.yaml

Create a security-managers team.
Fixes #112 
-    sub project contributors (incl. code owners) have write rights on all …

Create security-managers team

---

config.yaml

This reduces dependence/load on @thomwiggers, who is not able to contribute to OQS to the same degree as before.
I added the default list of maintainers/release managers while keeping Thom on both teams.
-    sub project committers have write rights on all …

Add members to the liboqs-rust teams

---

config.yaml

The OQS 2024-12-05 TSC meeting discussed archiving this repository. Before doing so, I want to update the README.md accordingly. Hence I need write permissions temporarily on this repository.
-    sub project committers have write rights on all branches of the …

Add oqs-maintainers to openssl 1.1.1 repository

---

config.yaml

A few years @jschanck moved on to a new position and has not been active in OQS for some time. Removing him from our teams so that he doesn't get spammed with unwanted Github notifications (though of course we'd be happy to have him back if there was ever a reason for it!).
-    OQS and sub project release managers have maintainer rights on the sub projects but can themselves set/reset branch protection rules limiting write access to …

Remove jschanck from committers and codeowners

---

meetings/2024-12-10/minutes.md

TSC meeting minutes from 2024-12-10.

Add TSC 2024-12-10 minutes

---

README.md
security/reports/20241220-hqc-decaps.md
security/reports/YYYYMMDD-template.md
security/response-process.md

This PR proposes a security response process for OQS. Please read it over and provide feedback. I expect it will undergo a fair bit of revision, but hopefully this gives us a starting point.
I have left a number of comments requesting feedback on specific points throughout the document. These are clearly marked by COMMENT. I'll keep the PR in draft until all of these are removed.
Closes #60.

OQS security response process

---

config.yaml

An additional maintainer
-    sub project contributors (incl. code owners) have write rights on all branches except main on …

Add OQS-Provider Maintainer

---

config.yaml

As per now-merged PR https://github.com/open-quantum-safe/liboqs/pull/2120.
-    sub project contributors (incl. code …

Add @SWilson4 to liboqs-maintainers team

---

config.yaml

sort teams
update bots from write to admin to enable AWS benchmarking
This is to enable AWS benchmarking. As access to more repos is needed, this role will need to change. This is in support of [the work in this branch](https://github.com/open-quantum-safe/liboqs/tree/sw-benchmarks) by @SWilson4 
-    OQS and sub project release managers have maintainer rights on the sub projects but can themselves set/reset branch protection rules …

chore: update permissions

---

config.yaml

Bruce, @xuganyu96, is a Research Associate at the University of Waterloo and will be working on OQS. This PR adds his GitHub account to config.yml to give him relevant permissions. 
-    sub project committers have write rights on all branches of the sub …

Add Bruce to config.yml
